### ISSUE TITLE
ValueError: Empty certificate data

### ISSUE THREAD

**Issue by ckee83** [lwilletts/Legions-on-Unix#2]
First off, excellent work on this putting this together. I too have missed going fast. 
My problem is that `make` appears to run successfully, but then after launching the game, the downloader renders on screen and I get the following error in the console:

```
Traceback (most recent call last):
  File "Z:\legionslauncher\legionslauncher\update_thread.py", line 34, in run
  File "Z:\legionslauncher\legionslauncher\launcher_update.py", line 20, in update_launcher
  File "c:\Development\legionslauncher\pyenv\lib\site-packages\esky\__init__.py", line 691, in find_update
  File "c:\Development\legionslauncher\pyenv\lib\site-packages\esky\finder.py", line 186, in find_versions
  File "c:\Development\legionslauncher\pyenv\lib\site-packages\esky\finder.py", line 165, in open_url
  File "C:\Python27\Lib\urllib2.py", line 154, in urlopen
  File "C:\Python27\Lib\urllib2.py", line 437, in open
  File "C:\Python27\Lib\urllib2.py", line 550, in http_response
  File "C:\Python27\Lib\urllib2.py", line 469, in error
  File "C:\Python27\Lib\urllib2.py", line 409, in _call_chain
  File "C:\Python27\Lib\urllib2.py", line 656, in http_error_302
  File "C:\Python27\Lib\urllib2.py", line 431, in open
  File "C:\Python27\Lib\urllib2.py", line 449, in _open
  File "C:\Python27\Lib\urllib2.py", line 409, in _call_chain
  File "C:\Python27\Lib\urllib2.py", line 1240, in https_open
  File "C:\Python27\Lib\urllib2.py", line 1166, in do_open
  File "C:\Python27\Lib\httplib.py", line 1262, in __init__
  File "C:\Python27\Lib\ssl.py", line 440, in create_default_context
  File "C:\Python27\Lib\ssl.py", line 391, in load_default_certs
  File "C:\Python27\Lib\ssl.py", line 383, in _load_windows_store_certs
ValueError: Empty certificate data
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function SSL_CTX_new
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function ERR_get_error
```
Let me know if I can be any help

**Comment by lwilletts** [comment]
I haven't used this for several months. I'll have a look into it when I get a working system up in the new year. I'll forward the error message to @tomkins anyhow.

**Comment by tomkins** [comment]
Added a couple of workarounds to avoid SSL for launcher updates for now.

Will need to fix it at some point, but that can wait for another day.

**Comment by ckee83** [comment]
That got me up and running, TYVM!
